/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Cart: typeof import('./components/Cart.vue')['default']
    Category: typeof import('./components/Category.vue')['default']
    copy: typeof import('./components/NewArrivals copy.vue')['default']
    Customer: typeof import('./components/customer.vue')['default']
    CustomerReview: typeof import('./components/CustomerReview.vue')['default']
    DressStyle: typeof import('./components/DressStyle.vue')['default']
    HeadBar: typeof import('./components/HeadBar.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HomaPage: typeof import('./components/HomaPage.vue')['default']
    HomePage: typeof import('./components/HomePage.vue')['default']
    HomeTitle: typeof import('./components/HomeTitle.vue')['default']
    LoginToSale: typeof import('./components/LoginToSale.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    NewAchrive: typeof import('./components/NewAchrive.vue')['default']
    NewArrivals: typeof import('./components/NewArrivals.vue')['default']
    ProductCard: typeof import('./components/basic/ProductCard.vue')['default']
    ProductDetailPage: typeof import('./components/ProductDetailPage.vue')['default']
    RatetingReview: typeof import('./components/RatetingReview.vue')['default']
    Recommend: typeof import('./components/Recommend.vue')['default']
    Recomment: typeof import('./components/Recomment.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Topselling: typeof import('./components/Topselling.vue')['default']
    TopSelling: typeof import('./components/TopSelling.vue')['default']
  }
}
